# Generated by Django 3.2.5 on 2021-10-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211005_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='application1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application1', to='shop.productapplication'),
        ),
        migrations.AddField(
            model_name='product',
            name='application2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application2', to='shop.productapplication'),
        ),
        migrations.AddField(
            model_name='product',
            name='application3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application3', to='shop.productapplication'),
        ),
        migrations.AddField(
            model_name='product',
            name='application4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application4', to='shop.productapplication'),
        ),
        migrations.AddField(
            model_name='product',
            name='application5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application5', to='shop.productapplication'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.productbrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory1', to='shop.productsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory2', to='shop.productsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory3', to='shop.productsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory4', to='shop.productsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory5', to='shop.productsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory6', to='shop.productsubcategory'),
        ),
    ]
