# Generated by Django 3.2.5 on 2021-10-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211005_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='productimages/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='productimages/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='productimages/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application1', to='shop.productapplication'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application2', to='shop.productapplication'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application3', to='shop.productapplication'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application4', to='shop.productapplication'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application5', to='shop.productapplication'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory2', to='shop.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory3', to='shop.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory4', to='shop.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory5', to='shop.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory6', to='shop.productsubcategory'),
        ),
    ]
