# Generated by Django 3.2.5 on 2021-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211005_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='long_desc',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.TextField(default='', max_length=200),
        ),
    ]
