# Generated by Django 3.2.5 on 2021-10-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211005_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulfilmentpartner',
            options={'verbose_name_plural': 'Fulfilment partners'},
        ),
        migrations.AlterModelOptions(
            name='productapplication',
            options={'verbose_name_plural': 'Product Applications'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name_plural': 'Product brands'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name_plural': 'Product sub categories'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
