# Generated by Django 3.2.5 on 2021-10-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211006_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfilmentpartner',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
